function tempdecs = get_decision(trial, eventvec, eventKey)

% 'Dec Lick (Pre)';
% 'Dec Lick (Stim)';
% 'Dec Lick (ED)';
% 'Dec Lick (LD)';
% 'Dec Lick (test)';
% 'Dec Lick (report)';
% 'Dec No Lick (Pre)';
% 'Dec No Lick (Stim)';
% 'Dec No Lick (ED)';
% 'Dec No Lick (LD)';
% 'Dec No Lick (test)';
% 'Dec No Lick (report)';

is_Lick = strcmp(trial.decision,'Hit')|strcmp(trial.decision,'FA');
is_No_lick = strcmp(trial.decision,'Miss')|strcmp(trial.decision,'CR');

is_Hit = strcmp(trial.decision,'Hit');
is_Miss = strcmp(trial.decision,'Miss');
is_FA = strcmp(trial.decision,'FA');
is_CR = strcmp(trial.decision,'CR');

[Pre, Cue, Early_delay, Late_delay, ~, Target, Report] = get_times(eventvec, eventKey);

tempdecs = [Pre*is_Lick;...
            Cue*is_Lick;...
            Early_delay*is_Lick;...
            Late_delay*is_Lick;...
            Target*is_Lick;...
            Report*is_Lick;...
            Pre*is_No_lick;...
            Cue*is_No_lick;...
            Early_delay*is_No_lick;...
            Late_delay*is_No_lick;...
            Target*is_No_lick;...
            Report*is_No_lick;...
            Target * is_Hit + Report * is_Hit;...
            Target * is_Miss + Report * is_Miss;...
            Target * is_FA + Report * is_FA;...
            Target * is_CR + Report * is_CR;...
            ];