function [catvectors] = get_category(trial, eventvec, eventKey)
 
% 'Cat M (Pre)';
% 'Cat M (sample)';
% 'Cat M (ED)';
% 'Cat M (LD)';
% 'Cat M (test)';
% 'Cat M (report)';
% 'Cat NM (Pre)';
% 'Cat NM (sample)';
% 'Cat NM (ED)';
% 'Cat NM (LD)';
% 'Cat NM (test)';
% 'Cat NM (report)';

is_M = strcmp(trial.direction_1,trial.direction_2);
is_NM = ~strcmp(trial.direction_1,trial.direction_2);

[Pre, Cue, Early_delay, Late_delay, ~, Target, Report] = get_times(eventvec, eventKey);

catvectors = [Pre*is_M;...
            Cue*is_M;...
            Early_delay*is_M;...
            Late_delay*is_M;...
            Target*is_M;...
            Report*is_M;...
            Pre*is_NM;...
            Cue*is_NM;...
            Early_delay*is_NM;...
            Late_delay*is_NM;...
            Target*is_NM;...
            Report*is_NM];